language: java
jdk:
- oraclejdk11
deploy:
  provider: heroku
  api_key:
    secure: bzTR12nP7S9VG+dJ/Bq57DrxvLD0dsD5WUDamJEc/X5Y9I4QtuEqv0hyfzOwWVgZEOpuBD3MM+fqGnOy+QQG/TUTCmWt513HY3lVFcdj32hYEon3t4gXrBAd5CxAlco21JXnr9owbx/T+1pzcpQ71M5QqJiIOrwZgEWRmV+82be1qOwkL9quqzWqTcrZMOA4UHQ7Iw6WAHhbnyQY6vAaPGgDSb+WFKNAuJ3zfcN62X9aS/2so18nPNI1jcOkeQgakTzaiFkgZ2uNy25ZzeNWTC3sPlAbk5ksyawuezwIY5w0m27y/yd7N5kgNZoJUlh2wuTrNYgAgZnHwwyjX1rgglmOMK6RAN/fAriP3IHu6tvVIOWY4+yA6sFqahHyQkPCbZsmSrtbqaQa24E+TOkkkq5O1VI1r4tkGmpHI1dnXBq9J8J+oDUI7ZrybL6j/tTI1+nborDWud8y4mUkzbFqtpJ6Cr4cVx2uLODpBiC6d8m8PTyccuVZRevue+6faJg9xIghTerItyXI7OeCVSwjDuT5+EOubPDy8uUrDSujAB5Mnf4FHyLPCmFCBBovPZYVsM/Hcf5DcLvsTJ9+iR++PfAzQbVmyG2rrNXf+7ZSQfVi1nhX9r9AWkp/YayushLrIBpKA13CnK5q5ypYOIgbXCoI/hpRXr06sVIWko+3Gdc=
  app: java14-demo
