language: java
jdk:
- oraclejdk11
deploy:
  provider: heroku
  api_key:
    secure: QJaWY+n6K1iyTYDUEQTaBiGzyxhk/0eMUcUkFFvvJPaJmPq7tG3JFK1R9oIh9MU9uWKpDCbZBAVGmN7QlMXWJcV8yFar1kMLbgMuKrnC4naH6Ld/eSt3gAhs0gYMQ+O/ESkO8k/x0+PC4AdiOVquChSkTe0yYQgI8U9HaIZPpsCNtlllCOYbDrAeinqFA7SECwyl5GOkSfsRXeSecYGEYK75h4bNKFYSD+uaoyVhxIPc77MupAynPjeZOuDGNztx9Wr1koCJH/LKxWyWZI3XqLOR8/mR6Niwe2z3eNtGGbxN2bEOZjWIQP3FxGVsufyLxUEoyZsmBMnzGEW7FrUC8F0TcEBOnMpOWMw5cJ3OY8Lqdc/W77wJ95LLmj/b+l1CbNH9CtHfFgkX6OOuHZk6TsuGlL9YEl8fabp1Awuf/Jciq5MnZCsGbjiX3lPer+uJ3y3wjaKlJQWOHFgw1ry00LHyhcNjTUOxAQSeQGs287ngBMfvrTYgJECdnUKXm8el4lf0MsqJ/yCN47Cy3ORd7XcpKi+DRzZYho9Q0GoBZ7Dcv7e9WXY6SOvrj9TiHETP11HPefsyxg/WSwa3xbBp4JiaiW+0wVu58MkIhKdPEnWIWCvRIz4Fr7XKvESts8LPQGatY210nC0+AedaMswVoNnID+dSYuM3oYYimQzt+O8=
  app: java14-demo
